
--CREATE DATABASE SPA



--CLIENTES SEGUN SU GENERO
 --CON EL SIGUIENTE DATO SE PODRIA CREER UNA PROMOCION ESPECIAL POR GENERO DE CADA SUCURSAL
SELECT CASE  
		   WHEN Sexo = '0' THEN 'MUJER' 
		   WHEN Sexo = '1' THEN 'HOMBRE' 
	   ELSE 'NO DEFINIDO' END AS 'GENERO',
	   COUNT(Sexo) AS 'CANTIDAD',(COUNT(Sexo)*100)/50 AS 'PORCENTAJE DE VISITA POR GENERO SUCURSAL CENTRO' 
FROM SPA_Centro WHERE PromVisit>=1 GROUP BY Sexo ORDER BY COUNT(Sexo) DESC

 SELECT CASE  
		   WHEN Sexo = '0' THEN 'MUJER' 
		   WHEN Sexo = '1' THEN 'HOMBRE' 
	   ELSE 'NO DEFINIDO' END AS 'GENERO',
	   COUNT(Sexo) AS 'CANTIDAD',(COUNT(Sexo)*100)/50 AS 'PORCENTAJE DE VISITA POR GENERO SUCURSAL ESCALON' 
FROM SPA_Escalon WHERE PromVisit>=1 GROUP BY Sexo ORDER BY COUNT(Sexo) DESC

 SELECT CASE  
		   WHEN Sexo = '0' THEN 'MUJER' 
		   WHEN Sexo = '1' THEN 'HOMBRE' 
	   ELSE 'NO DEFINIDO' END AS 'GENERO',
	   COUNT(Sexo) AS 'CANTIDAD',(COUNT(Sexo)*100)/50 AS 'PORCENTAJE DE VISITA POR GENERO SUCURSAL SANTA TECLA' 
FROM SPA_SantaTecla WHERE PromVisit>=1 GROUP BY Sexo ORDER BY COUNT(Sexo) DESC



--ANALISIS SEGUN SU EDAD MINIMA Y MAXIMA, INGRESOS MINIMOS E INGRESOS MAXIMOS Y UN PROMEDIO DE INGRESOS PARA PROMOVER ALGUNA OFERTA
SELECT 'SUCURSAL CENTRO', MIN(edad) AS 'Edad Minima',MAX(Edad) AS 'Edad Maxima', AVG(ingresos) AS 'Ingresos Promedio',
MIN(ingresos) AS 'Ingresos Minimos',MAX(ingresos) AS 'Ingresos Maximos' FROM SPA_Centro WHERE PromVisit BETWEEN  5 AND 7


SELECT 'SUCURSAL ESCALON', MIN(edad) AS 'Edad Minima',MAX(Edad) AS 'Edad Maxima', AVG(ingresos) AS 'Ingresos Promedio',
MIN(ingresos) AS 'Ingresos Minimos',MAX(ingresos) AS 'Ingresos Maximos' FROM SPA_Escalon WHERE PromVisit BETWEEN  5 AND 7


SELECT 'SUCURSAL SANTA TECLA', MIN(edad) AS 'Edad Minima',MAX(Edad) AS 'Edad Maxima', AVG(ingresos) AS 'Ingresos Promedio',
MIN(ingresos) AS 'Ingresos Minimos',MAX(ingresos) AS 'Ingresos Maximos' FROM SPA_SantaTecla WHERE PromVisit BETWEEN  5 AND 7


--SERVICIOS QUE SON MAS VISITADOS (SE PUEDE VARIAR EL PROMVISIT PARA VER OTRO TIPO DE INFORMACION)
SELECT COUNT(*) AS 'Sauna', (COUNT(*)*100)/50 AS 'PORCENTAJE DE CLIENTES QUE PREFIEREN SAUNA' FROM SPA_Centro WHERE PromVisit BETWEEN  1 AND 7 AND Sauna = 1 
SELECT COUNT(*) AS 'Masaje', (COUNT(*)*100)/50 AS 'PORCENTAJE DE CLIENTES QUE PREFIEREN MAJE' FROM SPA_Centro WHERE PromVisit BETWEEN  1 AND 7 AND Masaje = 1 
SELECT COUNT(*) AS 'Hidro', (COUNT(*)*100)/50 AS 'PORCENTAJE DE CLIENTES QUE PREFIEREN HIDRO' FROM SPA_Centro WHERE PromVisit BETWEEN  1 AND 7 AND Hidro = 1 
SELECT COUNT(*) AS 'Yoga', (COUNT(*)*100)/50 AS 'PORCENTAJE DE CLIENTES QUE PREFIEREN YOGA' FROM SPA_Centro WHERE PromVisit BETWEEN  1 AND 7 AND Yoga = 1 

--SERVICIOS QUE SON MAS VISITADOS (SE PUEDE VARIAR EL PROMVISIT PARA VER OTRO TIPO DE INFORMACION)
SELECT COUNT(*) AS 'Sauna', (COUNT(*)*100)/50 AS 'PORCENTAJE DE CLIENTES QUE PREFIEREN SAUNA' FROM SPA_Escalon WHERE PromVisit BETWEEN  1 AND 7 AND Sauna = 1 
SELECT COUNT(*) AS 'Masaje', (COUNT(*)*100)/50 AS 'PORCENTAJE DE CLIENTES QUE PREFIEREN MAJE' FROM SPA_Escalon WHERE PromVisit BETWEEN  1 AND 7 AND Masaje = 1 
SELECT COUNT(*) AS 'Hidro', (COUNT(*)*100)/50 AS 'PORCENTAJE DE CLIENTES QUE PREFIEREN HIDRO' FROM SPA_Escalon WHERE PromVisit BETWEEN  1 AND 7 AND Hidro = 1 
SELECT COUNT(*) AS 'Yoga', (COUNT(*)*100)/50 AS 'PORCENTAJE DE CLIENTES QUE PREFIEREN YOGA' FROM SPA_Escalon WHERE PromVisit BETWEEN  1 AND 7 AND Yoga = 1 

--SERVICIOS QUE SON MAS VISITADOS (SE PUEDE VARIAR EL PROMVISIT PARA VER OTRO TIPO DE INFORMACION)
SELECT COUNT(*) AS 'Sauna', (COUNT(*)*100)/50 AS 'PORCENTAJE DE CLIENTES QUE PREFIEREN SAUNA' FROM SPA_SantaTecla WHERE PromVisit BETWEEN  1 AND 7 AND Sauna = 1 
SELECT COUNT(*) AS 'Masaje', (COUNT(*)*100)/50 AS 'PORCENTAJE DE CLIENTES QUE PREFIEREN MAJE' FROM SPA_SantaTecla WHERE PromVisit BETWEEN  1 AND 7 AND Masaje = 1 
SELECT COUNT(*) AS 'Hidro', (COUNT(*)*100)/50 AS 'PORCENTAJE DE CLIENTES QUE PREFIEREN HIDRO' FROM SPA_SantaTecla WHERE PromVisit BETWEEN  1 AND 7 AND Hidro = 1 
SELECT COUNT(*) AS 'Yoga', (COUNT(*)*100)/50 AS 'PORCENTAJE DE CLIENTES QUE PREFIEREN YOGA' FROM SPA_SantaTecla WHERE PromVisit BETWEEN  1 AND 7 AND Yoga = 1 



--CLIENTES SEGUN SU EDAD PARA VERIFICAR ENTRE QUE EDAD SON MAS PERSONAS 
--CON ESTE DATO PODEMOS SABER ENTRE QUE EDADES NOS VISITAN MAS PERSONAS
SELECT Edad, COUNT(EDAD) AS 'CONTEO DE EDADES' FROM SPA_Centro GROUP BY EDAD ORDER BY COUNT(EDAD) DESC
SELECT Edad, COUNT(EDAD) AS 'CONTEO DE EDADES' FROM SPA_Escalon GROUP BY EDAD ORDER BY COUNT(EDAD) DESC
SELECT Edad, COUNT(EDAD) AS 'CONTEO DE EDADES' FROM SPA_SantaTecla GROUP BY EDAD ORDER BY COUNT(EDAD) DESC


SELECT * FROM SPA_Centro ORDER BY PromVisit DESC